name: "main"
on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install

  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm lint

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm test

      
