name: "main"
on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup
         run: make setup
      - name: start
         run: make start  
  linter:
    runs-on: ubuntu-latest
      - uses: actions/checkout@v3
      - run: make lint
  test:
    runs-on: ubuntu-latest
    - uses: actions/checkout@v3
    - run: make test

      
